version: '3.8'
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DBNAME: craveessa
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
    volumes:
      - ./:/app
      - ./uploads:/app/uploads

volumes:
  mongo_data:
  redis_data:
